// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// JacobiCpp
List JacobiCpp(NumericMatrix x, bool only_values, double eps);
RcppExport SEXP JacobiEigen_JacobiCpp(SEXP xSEXP, SEXP only_valuesSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type only_values(only_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    __result = Rcpp::wrap(JacobiCpp(x, only_values, eps));
    return __result;
END_RCPP
}
